2025-04-10 12:45:57 - ArithmaticApp - DEBUG - Adding 5 + 2 = 7
2025-04-10 12:45:57 - ArithmaticApp - DEBUG - Subtracting 5 - 2 = 3
2025-04-10 12:45:57 - ArithmaticApp - DEBUG - Multiplying 5 * 2 = 10
2025-04-10 12:45:57 - ArithmaticApp - ERROR - Exception occurred during division
Traceback (most recent call last):
  File "d:\New folder\MLOps\1-basic python\logging_app.py", line 36, in division
    result = a / b
ZeroDivisionError: division by zero
2025-04-10 12:45:57 - ArithmaticApp - DEBUG - Dividing 10 / 2 = 5.0
2025-04-10 12:48:01 - ArithmaticApp - DEBUG - Adding 5 + 2 = 7
2025-04-10 12:48:01 - ArithmaticApp - DEBUG - Subtracting 5 - 2 = 3
2025-04-10 12:48:01 - ArithmaticApp - DEBUG - Multiplying 5 * 2 = 10
2025-04-10 12:48:01 - ArithmaticApp - ERROR - Exception occurred during division
2025-04-10 12:48:01 - ArithmaticApp - DEBUG - Dividing 10 / 2 = 5.0
